id: "feedback"
name: "AGUI Run Feedback"
description: "Test feedback skill."
suggestions:
- "What kind of queries can I make about recent feedback?"
- "List ten most recent AGUI feedback runs"
- "Show run info for third feedback entry in 'opened' state"


agent:
  template_id: "default_chat"
  system_prompt: |
    You are a friendly agent.  Use the supplied skills as needed when
    replying to the user's prompts.

tools:
  - tool_name: "soliplex.tools.get_current_datetime"
  - tool_name: "soliplex.tools.agui_run_feedback.query_recent_feedback"
  - tool_name: "soliplex.tools.agui_run_feedback.get_feedback_run_info"
  - tool_name: "soliplex.tools.agui_run_feedback.review_recent_feedback"
  - tool_name: "soliplex.tools.agui_run_feedback.resolve_recent_feedback"
