"""Functional (black-box) test for the Soliplex project generator.

Unlike the unit suite (which mocks the seams), this drives the real CLI
end-to-end: it runs
``skills/soliplex-template/scripts/generate_soliplex_project.py`` as a
subprocess (secrets generated by default) and real ``git``, then verifies the
generated
project renders cleanly, the parameters propagate consistently, the secret
and git side effects actually happened, the rendered ``docker-compose.yml`` is
valid to Docker, and the ``postgres`` service (whose ``init.sh`` + secret
wiring is itself generated) starts and reports healthy.

Every live dependency is gated and **skips with a warning** when absent:
git/bash/openssl for the generation step, and the docker CLI/daemon for the
``docker compose`` tiers.

This tree is opt-in -- it is not in ``testpaths``. Run it with:

    uv run --group dev pytest tests/functional --no-cov
"""

from __future__ import annotations

import importlib.util
import json
import os
import pathlib
import shutil
import stat
import subprocess
import sys
import tomllib
import warnings

import pytest

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_SCRIPT = (
    _REPO_ROOT
    / "skills"
    / "soliplex-template"
    / "scripts"
    / "generate_soliplex_project.py"
)

# Non-default parameters: prove substitution propagates and use high host ports
# unlikely to collide with anything already running on the developer's machine.
_PARAMS = {
    "project_name": "soliplex-functest",
    "server_name": "functest.local",
    "ollama_base_url": "http://ollama.invalid:11434",
    "agui_db": "functest_agui",
    "authz_db": "functest_authz",
    "nginx_http": 19000,
    "nginx_https": 19443,
    "ingester_port": 18765,
    "docling_port": 15001,
    "postgres_port": 15432,
    # A docs dir the template does NOT ship, so ensure_runtime_dirs creates it
    # empty and drops a .gitkeep (exercising that branch + the compose mount).
    "docs_dir": "rag/inbox",
    # Pin a (fictional) frontend release tag to prove version selection lands
    # in nginx/Dockerfile as a /releases/tags/<tag> API URL.
    "frontend_version": "v9.9.9-test",
}

_GEN_TOOLS = ("git", "bash", "openssl")


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------
def _compose(cwd, *args):
    """Run ``docker compose <args>`` in ``cwd``; return its result."""
    return subprocess.run(
        ["docker", "compose", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
    )


def _read(out, *parts):
    return out.joinpath(*parts).read_text(encoding="utf-8")


# --------------------------------------------------------------------------
# Gating fixtures (skip-with-warning)
# --------------------------------------------------------------------------
@pytest.fixture
def docker_required():
    """Skip (with a warning) unless docker CLI + compose plugin are usable."""
    if shutil.which("docker") is None:
        warnings.warn(
            "docker not on PATH; skipping live-Docker functional tests",
            stacklevel=2,
        )
        pytest.skip("docker CLI not available")
    if _compose(_REPO_ROOT, "version").returncode != 0:
        warnings.warn(
            "`docker compose` unusable; skipping live-Docker tests",
            stacklevel=2,
        )
        pytest.skip("docker compose plugin not usable")


@pytest.fixture
def docker_daemon_required(docker_required):
    """Skip (with a warning) unless the docker daemon is reachable."""
    if (
        subprocess.run(
            ["docker", "info"], capture_output=True, text=True
        ).returncode
        != 0
    ):
        warnings.warn(
            "docker daemon unreachable; skipping `up` functional test",
            stacklevel=2,
        )
        pytest.skip("docker daemon not reachable")


# --------------------------------------------------------------------------
# Generate the project once for the module.
# --------------------------------------------------------------------------
@pytest.fixture(scope="module")
def generated_project(tmp_path_factory):
    """Run the real generator (subprocess) and yield ``(out, params)``."""
    missing = [t for t in _GEN_TOOLS if shutil.which(t) is None]
    if missing:
        warnings.warn(
            f"missing {missing}; skipping generation functional tests",
            stacklevel=2,
        )
        pytest.skip(f"generation needs {', '.join(_GEN_TOOLS)}")

    work = tmp_path_factory.mktemp("functest")
    out = work / "project"
    params_file = work / "params.json"
    params_file.write_text(json.dumps(_PARAMS), encoding="utf-8")

    result = subprocess.run(
        [
            sys.executable,
            str(_SCRIPT),
            "--out",
            str(out),
            "--params",
            str(params_file),
            # secrets generation defaults on; this exercises that default
            # end-to-end (no --generate-secrets flag needed).
            "--disable-gpg-sign",
        ],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"generator failed (rc={result.returncode}):\n"
        f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )
    return out, _PARAMS


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------
def test_no_leftover_mako_files(generated_project):
    out, _params = generated_project

    leftover = list(out.rglob("*.mako"))

    assert leftover == []


def test_key_artifacts_exist(generated_project):
    out, _params = generated_project

    expected = [
        "docker-compose.yml",
        ".env",
        "pyproject.toml",
        "README.md",
        "backend/environment/installation.yaml",
        "nginx/nginx.conf",
        "postgres/config/init.sh",
        "scripts/generate-secrets.sh",
    ]

    missing = [rel for rel in expected if not (out / rel).is_file()]
    assert missing == []


def test_parameters_substituted(generated_project):
    out, params = generated_project

    compose = _read(out, "docker-compose.yml")
    nginx = _read(out, "nginx/nginx.conf")
    installation = _read(out, "backend/environment/installation.yaml")
    init_sh = _read(out, "postgres/config/init.sh")
    pyproject = _read(out, "pyproject.toml")
    readme = _read(out, "README.md")

    assert f"name: {params['project_name']}" in compose
    assert f"{params['nginx_http']}:9000" in compose
    assert f"{params['postgres_port']}:5432" in compose
    assert f"server_name {params['server_name']};" in nginx
    assert f"{params['project_name']}-conf" in installation
    assert params["agui_db"] in init_sh
    assert params["authz_db"] in init_sh
    assert f'name = "{params["project_name"]}"' in pyproject
    assert params["project_name"] in readme
    assert f"./{params['docs_dir']}:/docs" in compose


def test_cross_file_consistency(generated_project):
    out, params = generated_project

    compose = _read(out, "docker-compose.yml")
    installation = _read(out, "backend/environment/installation.yaml")
    init_sh = _read(out, "postgres/config/init.sh")

    # DB names are driven from one parameter into both files.
    assert params["agui_db"] in installation
    assert params["agui_db"] in init_sh
    assert params["authz_db"] in installation
    assert params["authz_db"] in init_sh
    # Every chosen host port lands in the compose mapping.
    for key in (
        "nginx_http",
        "nginx_https",
        "ingester_port",
        "docling_port",
        "postgres_port",
    ):
        assert f"{params[key]}:" in compose


def test_frontend_version_pinned_in_nginx_dockerfile(generated_project):
    out, params = generated_project

    dockerfile = _read(out, "nginx/Dockerfile")

    assert f"releases/tags/{params['frontend_version']}" in dockerfile
    assert "releases/latest" not in dockerfile


def test_escaped_literals_survived(generated_project):
    out, _params = generated_project

    compose = _read(out, "docker-compose.yml")
    haiku = _read(out, "haiku.rag/haiku.rag.yaml")

    # <%text>-escaped runtime interpolations must reach the output verbatim.
    assert "${OLLAMA_BASE_URL}" in compose
    assert "${INGESTER_TOKEN:-secret}" in compose
    assert "__INGESTER_TOKEN__" in haiku


def test_ingester_wired_to_postgres_queue(generated_project):
    # #68: the ingester job queue is a dedicated Postgres database
    # (soliplex_ingester), created by init.sh and addressed by a dburi whose
    # password is sed-substituted from the ingester_db_password secret.
    out, _params = generated_project

    compose = _read(out, "docker-compose.yml")
    init_sh = _read(out, "postgres/config/init.sh")
    haiku = _read(out, "haiku.rag/haiku.rag.yaml")

    assert (
        "dburi: postgresql+asyncpg://soliplex_ingester:"
        "__INGESTER_DB_PASSWORD__@postgres/soliplex_ingester" in haiku
    )
    assert "CREATE DATABASE soliplex_ingester;" in init_sh
    assert "ingester_db_password:\n      file: ./.secrets/" in compose


def test_runtime_dirs_have_gitkeep(generated_project):
    out, params = generated_project

    keeps = [
        "backend/uploads/rooms/.gitkeep",
        "backend/uploads/threads/.gitkeep",
        f"{params['docs_dir']}/.gitkeep",
    ]

    missing = [rel for rel in keeps if not (out / rel).is_file()]
    assert missing == []


def test_runtime_bind_mount_dirs_are_git_tracked(generated_project):
    # #50/#51: every host bind-mount source dir must be committed so it
    # survives a fresh clone. A missing source is recreated root-owned by the
    # Docker daemon, after which the uid-1000 ingester/backend can't write it
    # (e.g. the ingester can't write the LanceDB under /data). Tracked
    # placeholders keep the directories present.
    out, params = generated_project
    expected = {
        "rag/db/README.md",
        "backend/uploads/rooms/.gitkeep",
        "backend/uploads/threads/.gitkeep",
        "backend/sandbox/workdirs/README.md",
        f"{params['docs_dir']}/.gitkeep",
    }

    tracked = set(
        subprocess.run(
            ["git", "ls-files"],
            cwd=out,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split()
    )

    assert expected <= tracked


def test_runtime_data_stays_gitignored(generated_project):
    # The bind-mount dirs are tracked, but the data written into them at
    # runtime (LanceDB, uploads, sandbox scratch) must remain ignored so it
    # never lands in the project's git history. (The ingester job queue now
    # lives in Postgres, not a file under rag/db/.)
    out, _params = generated_project
    data_paths = [
        "rag/db/haiku.rag.lancedb/chunks.lance",
        "backend/uploads/rooms/secret.pdf",
        "backend/sandbox/workdirs/run1/scratch.py",
    ]

    ignored = subprocess.run(
        ["git", "check-ignore", *data_paths],
        cwd=out,
        capture_output=True,
        text=True,
    ).stdout.split()

    assert set(ignored) == set(data_paths)


def test_env_file_written(generated_project):
    out, params = generated_project

    env = _read(out, ".env")

    assert f"OLLAMA_BASE_URL={params['ollama_base_url']}" in env
    assert "INGESTER_TOKEN=" in env
    # UID/GID default to the host operator running the generator (this test
    # process); compose reads them and the generated secrets are owned by them.
    assert f"PUID={os.getuid()}" in env
    assert f"PGID={os.getgid()}" in env


# --------------------------------------------------------------------------
# Installable package: src/<package_name>/ + tests/ + wiring
#
# project_name "soliplex-functest" normalises to the import name
# "soliplex_functest".
# --------------------------------------------------------------------------
_PACKAGE = "soliplex_functest"


def test_src_package_synthesized(generated_project):
    out, _params = generated_project

    pkg = out / "src" / _PACKAGE

    missing = [
        name for name in ("tools.py", "views.py") if not (pkg / name).is_file()
    ]
    assert missing == []


def test_tests_tree_synthesized(generated_project):
    out, _params = generated_project

    tests = out / "tests" / "unit"

    missing = [
        name
        for name in ("test_tools.py", "test_views.py")
        if not (tests / name).is_file()
    ]
    assert missing == []


def test_pyproject_declares_installable_package(generated_project):
    out, _params = generated_project

    pyproject = _read(out, "pyproject.toml")

    assert "[build-system]" in pyproject
    assert "hatchling" in pyproject
    assert f'packages = ["src/{_PACKAGE}"]' in pyproject
    assert "[tool.pytest.ini_options]" in pyproject


def test_pyproject_records_generation_manifest(generated_project):
    out, _params = generated_project

    data = tomllib.loads(_read(out, "pyproject.toml"))

    manifest = data["tool"]["soliplex-template"]
    assert manifest["skill_name"] == "soliplex-template"
    # version / source_commit / generated may be blank in-repo (the source
    # SKILL.md is unstamped); the keys are present regardless.
    assert {"skill_version", "skill_source_commit", "skill_generated"} <= set(
        manifest
    )
    params = manifest["params"]
    assert params["project_name"] == "soliplex-functest"
    assert params["nginx_https"] == 19443  # int preserved
    assert params["include_gitea"] is False  # bool preserved
    assert params["include_tui"] is False  # bool preserved
    assert params["ingester_token"] == "<redacted>"  # secret never recorded


def test_custom_room_references_package_tool(generated_project):
    out, _params = generated_project

    room = _read(out, "backend/environment/rooms/custom/room_config.yaml")

    assert f'tool_name: "{_PACKAGE}.tools.greeting"' in room


def test_installation_registers_package_router(generated_project):
    out, _params = generated_project

    installation = _read(out, "backend/environment/installation.yaml")

    assert f'router_name: "{_PACKAGE}.views.router"' in installation
    assert '- "./rooms/custom"' in installation


def test_compose_puts_src_on_backend_pythonpath(generated_project):
    out, _params = generated_project

    compose = _read(out, "docker-compose.yml")

    assert "PYTHONPATH: /app/src" in compose
    assert 'source: "./src"' in compose


def test_default_project_omits_tui_service(generated_project):
    out, _params = generated_project

    compose = _read(out, "docker-compose.yml")

    # include_tui defaults off: no tui service, no tui/ build context...
    assert "\n  tui:\n" not in compose
    assert not (out / "tui").exists()
    # ...but the CLI client (bundled in the backend image) is still documented.
    install_doc = _read(out, "docs/getting-started/installation.md")
    assert "docker compose exec backend" in install_doc
    assert "soliplex-tui --url http://localhost:8000" in install_doc
    # The web-TUI-behind-nginx note is gated on include_tui, so absent here.
    assert "/tui/>" not in install_doc


def test_generated_package_is_importable(generated_project):
    out, _params = generated_project
    # Hermetic: the stdlib-only tool imports off PYTHONPATH with no install.
    # (views.py needs fastapi, present only in the owner's soliplex env, so it
    # is exercised by the generated tests/unit/test_views.py, not here.)
    env = {
        **os.environ,
        "PYTHONPATH": str(out / "src"),
        "PYTHONDONTWRITEBYTECODE": "1",
    }

    result = subprocess.run(
        [
            sys.executable,
            "-c",
            f"import {_PACKAGE}.tools as t; print(t.greeting('Ada'))",
        ],
        capture_output=True,
        text=True,
        env=env,
    )

    assert result.returncode == 0, result.stderr
    assert "Ada" in result.stdout


# --------------------------------------------------------------------------
# Documentation site (Zensical)
#
# The generated project ships a parameterized Zensical docs site under docs/
# (paralleling the upstream template repo's site) plus a zensical.toml.
# --------------------------------------------------------------------------
_DOC_PAGES = (
    "docs/index.md",
    "docs/getting-started/installation.md",
    "docs/architecture/services.md",
    "docs/architecture/configuration.md",
    "docs/architecture/backend.md",
    "docs/operations/secrets.md",
    "docs/operations/rag.md",
    "docs/operations/ingester.md",
    "docs/custom-package.md",
)


def test_docs_site_synthesized(generated_project):
    out, _params = generated_project

    missing = [
        rel
        for rel in (*_DOC_PAGES, "zensical.toml")
        if not (out / rel).is_file()
    ]

    assert missing == []


def test_docs_are_parameterized(generated_project):
    out, params = generated_project

    zensical = _read(out, "zensical.toml")
    index = _read(out, "docs/index.md")
    custom = _read(out, "docs/custom-package.md")

    assert f'site_name = "{params["project_name"]}"' in zensical
    assert str(params["nginx_http"]) in index
    assert f"src/{_PACKAGE}" in custom


def test_docs_markdown_headings_survive_rendering(generated_project):
    # Mako treats a leading '##' as a comment; the templates wrap headings in
    # <%text> so Markdown headings survive. Guard against that regression in
    # both an authored doc and the README.
    out, _params = generated_project

    install = _read(out, "docs/getting-started/installation.md")
    readme = _read(out, "README.md")

    assert "## Prerequisites" in install
    assert "## Exposed ports" in install
    assert "## Documentation" in readme


def test_pyproject_includes_zensical_dev_dep(generated_project):
    out, _params = generated_project

    pyproject = _read(out, "pyproject.toml")

    assert "zensical" in pyproject


def test_docs_build_with_zensical(generated_project):
    out, params = generated_project
    # Hermetic: zensical is pure-Python (in this repo's dev group) and builds
    # the static site offline. Skip-with-warning if it isn't importable.
    if importlib.util.find_spec("zensical") is None:
        warnings.warn(
            "zensical not importable; skipping docs build test",
            stacklevel=2,
        )
        pytest.skip("zensical not installed")

    result = subprocess.run(
        [sys.executable, "-m", "zensical", "build", "--strict"],
        cwd=out,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert (out / "site" / "index.html").is_file()
    assert params["project_name"] in _read(out, "site", "index.html")


# --------------------------------------------------------------------------
# Side effects: secrets + git
# --------------------------------------------------------------------------
def test_secrets_generated_by_default(generated_project):
    out, _params = generated_project

    gen_files = sorted(p.name for p in (out / ".secrets").glob("*.gen"))

    assert gen_files == [
        "agui_db_password.gen",
        "authz_db_password.gen",
        "ingester_db_password.gen",
        "postgres_password.gen",
        "url_safe_token_secret.gen",
    ]
    for name in gen_files:
        mode = stat.S_IMODE((out / ".secrets" / name).stat().st_mode)
        # 0600: owner-only. The files are owned by PUID/PGID (here the host
        # operator running the generator), and the containers run as that same
        # uid/gid, so an owner-only mode is both sufficient and the right
        # secret hygiene -- no world-readable bits needed.
        assert mode == 0o600, f"{name} has mode {oct(mode)}"


def test_git_initialised_with_single_clean_commit(generated_project):
    out, _params = generated_project

    log = subprocess.run(
        ["git", "-C", str(out), "log", "--oneline"],
        capture_output=True,
        text=True,
    )
    status = subprocess.run(
        ["git", "-C", str(out), "status", "--porcelain"],
        capture_output=True,
        text=True,
    )

    assert (out / ".git").is_dir()
    assert len(log.stdout.strip().splitlines()) == 1
    assert status.stdout.strip() == ""  # .secrets/ and .env are gitignored


# --------------------------------------------------------------------------
# Docker: the rendered compose file is valid, and postgres comes up healthy.
# --------------------------------------------------------------------------
@pytest.mark.needs_docker
def test_docker_compose_config_valid(generated_project, docker_required):
    out, _params = generated_project

    result = _compose(out, "config", "-q")

    assert result.returncode == 0, result.stderr


@pytest.mark.needs_docker
def test_include_tui_renders_valid_compose(tmp_path, docker_required):
    missing = [t for t in _GEN_TOOLS if shutil.which(t) is None]
    if missing:
        pytest.skip(f"generation needs {', '.join(_GEN_TOOLS)}")
    out = tmp_path / "project"
    params_file = tmp_path / "params.json"
    params_file.write_text(
        json.dumps({**_PARAMS, "include_tui": True}), encoding="utf-8"
    )

    result = subprocess.run(
        [
            sys.executable,
            str(_SCRIPT),
            "--out",
            str(out),
            "--params",
            str(params_file),
            "--no-git",
            "--disable-gpg-sign",
        ],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    compose = _read(out, "docker-compose.yml")
    assert "\n  tui:\n" in compose
    assert (out / "tui" / "Dockerfile").exists()
    cfg = _compose(out, "config", "-q")
    assert cfg.returncode == 0, cfg.stderr


@pytest.fixture
def postgres_up(generated_project, docker_daemon_required):
    """Bring up only postgres (--wait), yield, and always tear down."""
    out, params = generated_project
    # config is a precondition: never attempt `up` on a file that won't parse.
    cfg = _compose(out, "config", "-q")
    if cfg.returncode != 0:
        pytest.fail(f"docker compose config failed:\n{cfg.stderr}")

    up = _compose(
        out, "up", "-d", "--wait", "--wait-timeout", "180", "postgres"
    )
    try:
        yield out, params, up
    finally:
        _compose(out, "down", "-v")


@pytest.mark.needs_docker
def test_postgres_service_comes_up_healthy(postgres_up):
    out, _params, up = postgres_up

    # `up --wait` returns 0 only once postgres reports healthy.
    assert up.returncode == 0, f"up failed:\n{up.stdout}\n{up.stderr}"

    ps = _compose(out, "ps", "--format", "json", "postgres")
    entries = [
        json.loads(line) for line in ps.stdout.splitlines() if line.strip()
    ]
    postgres = next(e for e in entries if e.get("Service") == "postgres")
    assert postgres.get("State") == "running"
    if postgres.get("Health"):  # healthcheck is defined, so this is present
        assert postgres["Health"] == "healthy"


@pytest.mark.needs_docker
def test_postgres_init_creates_databases_and_roles(postgres_up):
    # The generated postgres/config/init.sh (AUTO_CREATE_DATABASE defaults on)
    # runs on the fresh volume and creates a database + like-named role per
    # configured DB name. One round trip lists both catalogs. The stack uses
    # scram-sha-256 for every connection (including the socket), so feed psql
    # the generated superuser password via PGPASSWORD.
    out, params, _up = postgres_up
    password = _read(out, ".secrets", "postgres_password.gen")
    probe = (
        "SELECT 'db:' || datname FROM pg_database "
        "UNION ALL "
        "SELECT 'role:' || rolname FROM pg_roles"
    )

    result = _compose(
        out,
        "exec",
        "-T",
        "-e",
        f"PGPASSWORD={password}",
        "postgres",
        "psql",
        "-U",
        "postgres",
        "-d",
        "postgres",
        "-tAc",
        probe,
    )

    assert result.returncode == 0, result.stderr
    catalog = {
        line.strip() for line in result.stdout.splitlines() if line.strip()
    }
    expected = {
        f"db:{params['agui_db']}",
        f"db:{params['authz_db']}",
        "db:soliplex_ingester",
        f"role:{params['agui_db']}",
        f"role:{params['authz_db']}",
        "role:soliplex_ingester",
    }
    assert expected <= catalog, sorted(expected - catalog)
