# See:
# https://docs.python.org/3/library/logging.config.html#dictionary-schema-details
version: 1
disable_existing_loggers: false
formatters:

  default:
    format: "$asctime|$levelname|$name|$message"
    datefmt: "%Y-%m-%dT%H:%M:%S"
    style: "$"
    validate: true
    defaults:
        some_key: null

  soliplex-authn:
    format: "{name}|{asctime}|{levelname}|{message}"
    datefmt: "%Y-%m-%dT%H:%M:%S"
    style: "{"
    validate: true
    defaults:
        header_id: "<no-header-id>"

  soliplex:
    #format: "{name}|{asctime}|{levelname}|{email}|{message}"
    format: "{name}|{asctime}|{levelname}|{user_id}|{message}"
    datefmt: "%Y-%m-%dT%H:%M:%S"
    style: "{"
    validate: true
    defaults:
        header_id: "<no-header-id>"
        user_id: "<no-user-id>"

filters:

  # Add this filter to update log level on a logger from 'DEBUG' to 'INFO'.
  update_debug_to_info:
    (): "soliplex.loggers.UpdateLevels"
    update_levels:
      "DEBUG": "INFO"

handlers:

  console-default:
    class: "logging.StreamHandler"
    formatter: "default"
    #filters: []
    stream: "ext://sys.stdout"

  console-soliplex-authn:
    class: "logging.StreamHandler"
    formatter: "soliplex-authn"
    #filters: []
    stream: "ext://sys.stdout"

  console-soliplex:
    class: "logging.StreamHandler"
    formatter: "soliplex"
    #filters: []
    stream: "ext://sys.stdout"

loggers:

  soliplex:
    level: "INFO"
    propagate: false
    handlers:
      - "console-soliplex"

  soliplex.authn:
    level: "INFO"
    propagate: false
    handlers:
      - "console-soliplex-authn"
  # filters:
  #   - "update_debug_to_info"

  soliplex.authz:
    level: "INFO"
    propagate: false
    handlers:
      - "console-soliplex"
  # filters:
  #   - "update_debug_to_info"

root:
  level: "INFO"
  handlers:
    - "console-default"
