## summary: Conversational RAG; answers from the knowledge base
# Room generated by the 'soliplex-template' skill (scripts/add_room.py).
# Conversational RAG: the agent answers from the LanceDB knowledge base via
# the 'rag' skill.
id: "${room_id}"
name: "${name}"
description: "${description}"

suggestions:
  - "Summarize the key points of a document"
  - "Search the knowledge base for a topic"

agent:
  template_id: "${agent_template}"
  # To keep the prompt in its own file instead of inline, drop a 'prompt.txt'
  # beside this config and use:
  #system_prompt: "./prompt.txt"
  system_prompt: ${system_prompt_yaml}

tools:
  - tool_name: "soliplex.tools.get_current_datetime"
  - tool_name: "soliplex.tools.get_current_user"
  - tool_name: "soliplex.tools.file_uploads.list_thread_file_uploads"
  - tool_name: "soliplex.tools.file_uploads.get_thread_file_upload"
  #
  # 'greeting' comes from this project's own package
  # (src/${package_name}/tools.py; src/ is on the backend PYTHONPATH).
  # Replace or remove it as you build out your own tools.
  #
  - tool_name: "${package_name}.tools.greeting"

skills:
# A *filesystem* skill (a directory under a 'filesystem_skills_paths' root,
# also declared in installation.yaml 'skill_configs'), enabled here by name --
# e.g. image generation:
# installation_skill_names:
#   - "image-generation"

# *Entrypoint* skills addressed by 'kind' (the RAG skill is wired in below;
# add others the same way):
  skill_configs:

    - kind: "haiku.rag.skills.rag"
#
#     # Searched as one set. A name is what search results, documents and
#     # citations report, so it must be unique within the list; the
#     # location stays here in the config. Every database in the list must
#     # have been written with the same embedding model, since one query is
#     # embedded once for all of them.
#     #
      rag_databases:
         -
#          # optional, defaults to the stem
#          name: "${room_id}"
#          #
#          # Exactly one of 'rag_lancedb_stem' / 'rag_lancedb_override_path':
#          #
           rag_lancedb_stem: "${rag_stem}"
#          rag_lancedb_override_path: "../other.lancedb"
#        -
#          name: "other_db"
#          #
#          # Exactly one of 'rag_lancedb_stem' / 'rag_lancedb_override_path':
#          #
#          rag_lancedb_stem: "another_db"
#          rag_lancedb_override_path: "../another.lancedb"
#
#   # Compaction replaces earlier questions' evidence on the request with
#   # what was cited; the citation policy is what makes citations happen.
#   # Configuring compaction alone drops the evidence of any question the
#   # model did not cite for.
    - kind: "haiku.rag.skills.evidence_compaction"
    - kind: "haiku.rag.skills.citation_policy"

#   - kind: "<another-entrypoint-skill>"

      #
      # Per-room haiku.rag overrides: drop a 'haiku.rag.yaml' beside this
      # config (merged over the installation's); not an inline field.
      #

allow_mcp: false
