## summary: Search & answer from RAG, citing sources.
# Room generated by the 'soliplex-template' skill (scripts/add_room.py).
# Search & answer: the agent searches the knowledge base with the
# 'search_documents' tool and answers from the results (with citations).
id: "${room_id}"
name: "${name}"
description: "${description}"

suggestions:
  - "What does the knowledge base say about ...?"
  - "Find documents about ..."

agent:
  template_id: "${agent_template}"
  # To keep the prompt in its own file instead of inline, drop a 'prompt.txt'
  # beside this config and use:
  #system_prompt: "./prompt.txt"
  system_prompt: ${system_prompt_yaml}

tools:
  - tool_name: "soliplex.tools.rag.search_documents"
    #
    # Exactly one of 'rag_lancedb_stem' / 'rag_lancedb_override_path':
    #
    rag_lancedb_stem: "${rag_stem}"
    #
    # ... or 'rag_databases' to search several as one set: this tool takes
    # the same spelling as the RAG skill (see the commented block below).
    #

    search_documents_limit: 7

    # Apply haiku.rag config overrides local to this room:
    #haiku_rag_config: "./haiku.rag.yaml"

  #
  # 'greeting' comes from this project's own package
  # (src/${package_name}/tools.py; src/ is on the backend PYTHONPATH).
  # Replace or remove it as you build out your own tools.
  #
  - tool_name: "${package_name}.tools.greeting"

# --- Skills (optional) -----------------------------------------------------
# A *filesystem* skill enabled by name (declared in installation.yaml
# 'skill_configs'), or an *entrypoint* skill addressed directly by 'kind':
#
#skills:
#
#  installation_skill_names:
#    - "my-filesystem-skill"
#
#  skill_configs:
#    - kind: "haiku.rag.skills.rag"
#      #
#      # Searched as one set. A name is what search results, documents and
#      # citations report, so it must be unique within the list; the
#      # location stays here in the config. Every database in the list must
#      # have been written with the same embedding model, since one query is
#      # embedded once for all of them.
#      #
#      rag_databases:
#        -
#          # optional, defaults to the stem
#          name: "${room_id}"
#          #
#          # Exactly one of 'rag_lancedb_stem' / 'rag_lancedb_override_path':
#          #
#          rag_lancedb_stem: "${rag_stem}"
#          rag_lancedb_override_path: "../other.lancedb"
#        -
#          name: "other_db"
#          #
#          # Exactly one of 'rag_lancedb_stem' / 'rag_lancedb_override_path':
#          #
#          rag_lancedb_stem: "another_db"
#          rag_lancedb_override_path: "../another.lancedb"
#    #
#    # Compaction replaces earlier questions' evidence on the request with
#    # what was cited; the citation policy is what makes citations happen.
#    # Configuring compaction alone drops the evidence of any question the
#    # model did not cite for.
#    - kind: "haiku.rag.skills.evidence_compaction"
#    - kind: "haiku.rag.skills.citation_policy"

#
#      #
#      # Per-room haiku.rag overrides: drop a 'haiku.rag.yaml' beside this
#      # config (merged over the installation's); not an inline field.
#      # Don't also place a database in that file's 'lancedb.databases':
#      # naming one here as well is two placements for one room, and the
#      # room fails when it is used.
#      #

allow_mcp: false
