# See:
# https://docs.python.org/3/library/logging.config.html#dictionary-schema-details
version: 1
disable_existing_loggers: false
formatters:

  default:
    format: "$asctime|$levelname|$name|$message"
    datefmt: "%Y-%m-%dT%H:%M:%S"
    style: "$"
    validate: true
    defaults:
        some_key: null

filters:

  # Add this filter to update log level on a logger from 'DEBUG' to 'INFO'.
  update_debug_to_info:
    (): "soliplex.loggers.UpdateLevels"
    update_levels:
      "DEBUG": "INFO"

handlers:

  console:
    class: "logging.StreamHandler"
    formatter: "default"
    #filters: []
    stream: "ext://sys.stdout"

loggers:

  soliplex:
    level: "INFO"

  soliplex.authn:
    level: "INFO"
  # filters:
  #   - "update_debug_to_info"

  soliplex.authz:
    level: "INFO"

root:
  level: "INFO"
  handlers:
    - "console"
