## summary: Bare agent + system prompt; no tools or skills
# Room generated by the 'soliplex-template' skill (scripts/add_room.py).
# A minimal room: just an agent and a system prompt. Grow it by uncommenting
# the tools / skills examples below.
id: "${room_id}"
name: "${name}"
description: "${description}"

agent:
  template_id: "${agent_template}"
  # To keep the prompt in its own file instead of inline, drop a 'prompt.txt'
  # beside this config and use:
  #system_prompt: "./prompt.txt"
  system_prompt: ${system_prompt_yaml}

# --- Tools (optional) ------------------------------------------------------
# Give the agent callable tools by dotted import name. soliplex.tools.* ship
# with the backend; a tool from this project's own package (src/<pkg>/) is
# importable too -- src/ is on the backend PYTHONPATH (see docker-compose.yml).
#
#tools:
#  - tool_name: "soliplex.tools.get_current_datetime"
#  - tool_name: "soliplex.tools.get_current_user"
#  #
#  # 'greeting' comes from this project's own package
#  # (src/${package_name}/tools.py; src/ is on the backend PYTHONPATH):
#  #
#  - tool_name: "${package_name}.tools.greeting"

# --- Skills (optional) -----------------------------------------------------
# Two kinds of skill can attach to a room:
#
#  * a *filesystem* skill -- a directory under a 'filesystem_skills_paths'
#    root. It must also be declared in 'skill_configs' in installation.yaml;
#    enable it here by name under 'installation_skill_names'.
#
#  * an *entrypoint* skill -- a packaged skill addressed directly by its
#    'kind' under 'skill_configs' (e.g. the RAG skill, a sandbox skill).
#
#skills:
#
#  installation_skill_names:
#    - "my-filesystem-skill"
#
#  skill_configs:
#
#    - kind: "haiku.rag.skills.rag"
#      #
#      # Exactly one of 'rag_lancedb_stem' / 'rag_lancedb_override_path':
#      #
#      rag_lancedb_stem: "haiku.rag"
#      rag_lancedb_override_path: "../other.lancedb"
#      #
#      # Per-room haiku.rag overrides: drop a 'haiku.rag.yaml' beside this
#      # config (merged over the installation's); not an inline field.
#      #

allow_mcp: false
