id: "faux"
name: "Faux Agent Test"
description: "Testing faux agent"
agent:
  kind: "factory"
  factory_name: "soliplex.examples.faux_agent_factory"
  with_agent_config: true
tools:
  - tool_name: "soliplex.examples.faux_tool"
allow_mcp: false
