name: Notify Slack on New issue

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification when new issue is opened
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_NOTIFY_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "channel": "#soliplex",
              "username": "soliplex-template",
              "text": ":bell: New issue by *${{ github.event.issue.user.login }}*:\n*${{ github.event.issue.title }}*\n${{ github.event.issue.html_url }}",
              "icon_emoji": ":ghost:"
            }
